# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/AreaPersonale.qml) \
        $$quote($$BASEDIR/assets/CustomTimelineView.qml) \
        $$quote($$BASEDIR/assets/FermataDetail.qml) \
        $$quote($$BASEDIR/assets/Guida.qml) \
        $$quote($$BASEDIR/assets/Login.qml) \
        $$quote($$BASEDIR/assets/Ricerca.qml) \
        $$quote($$BASEDIR/assets/SolutionDetails.qml) \
        $$quote($$BASEDIR/assets/StatoTreno.qml) \
        $$quote($$BASEDIR/assets/StatoTrenoItalo.qml) \
        $$quote($$BASEDIR/assets/StatoTrenoRicerca.qml) \
        $$quote($$BASEDIR/assets/StazioneItem.qml) \
        $$quote($$BASEDIR/assets/StazioneRicerca.qml) \
        $$quote($$BASEDIR/assets/StazioneStato.qml) \
        $$quote($$BASEDIR/assets/Titolo.qml) \
        $$quote($$BASEDIR/assets/TrainDetail.qml) \
        $$quote($$BASEDIR/assets/ViaggioItem.qml) \
        $$quote($$BASEDIR/assets/Wait.qml) \
        $$quote($$BASEDIR/assets/dump.json) \
        $$quote($$BASEDIR/assets/dump_2_6.json) \
        $$quote($$BASEDIR/assets/dump_codici.json) \
        $$quote($$BASEDIR/assets/dump_coordinate.json) \
        $$quote($$BASEDIR/assets/fsnews.qml) \
        $$quote($$BASEDIR/assets/images/arrow-right-01-512.png) \
        $$quote($$BASEDIR/assets/images/background.png) \
        $$quote($$BASEDIR/assets/images/bg.png) \
        $$quote($$BASEDIR/assets/images/calendar-add-256x256.png) \
        $$quote($$BASEDIR/assets/images/cart.amd) \
        $$quote($$BASEDIR/assets/images/cart.png) \
        $$quote($$BASEDIR/assets/images/coins.jpg) \
        $$quote($$BASEDIR/assets/images/coins.png) \
        $$quote($$BASEDIR/assets/images/cross.png) \
        $$quote($$BASEDIR/assets/images/fs_logo.jpg) \
        $$quote($$BASEDIR/assets/images/fs_logo.png) \
        $$quote($$BASEDIR/assets/images/globe.png) \
        $$quote($$BASEDIR/assets/images/ic_forward.png) \
        $$quote($$BASEDIR/assets/images/ic_info.png) \
        $$quote($$BASEDIR/assets/images/ic_next.amd) \
        $$quote($$BASEDIR/assets/images/ic_next.png) \
        $$quote($$BASEDIR/assets/images/ic_open.png) \
        $$quote($$BASEDIR/assets/images/ic_reload.png) \
        $$quote($$BASEDIR/assets/images/ic_reply.png) \
        $$quote($$BASEDIR/assets/images/ic_search.png) \
        $$quote($$BASEDIR/assets/images/img_cartafr_base_red.gif) \
        $$quote($$BASEDIR/assets/images/img_cartafr_oro.gif) \
        $$quote($$BASEDIR/assets/images/img_cartafr_platino.gif) \
        $$quote($$BASEDIR/assets/images/italo_logo.png) \
        $$quote($$BASEDIR/assets/images/italo_logo_red.png) \
        $$quote($$BASEDIR/assets/images/item_background.png) \
        $$quote($$BASEDIR/assets/images/item_background_selected.png) \
        $$quote($$BASEDIR/assets/images/login.amd) \
        $$quote($$BASEDIR/assets/images/login.png) \
        $$quote($$BASEDIR/assets/images/login_round.png) \
        $$quote($$BASEDIR/assets/images/pdf.png) \
        $$quote($$BASEDIR/assets/images/redgrad.png) \
        $$quote($$BASEDIR/assets/images/stato_treno.amd) \
        $$quote($$BASEDIR/assets/images/stato_treno.png) \
        $$quote($$BASEDIR/assets/images/stato_treno_.png) \
        $$quote($$BASEDIR/assets/images/swap_icon.amd) \
        $$quote($$BASEDIR/assets/images/swap_icon.png) \
        $$quote($$BASEDIR/assets/images/swap_v.png) \
        $$quote($$BASEDIR/assets/images/swap_v_baseGreen.amd) \
        $$quote($$BASEDIR/assets/images/swap_v_baseGreen.png) \
        $$quote($$BASEDIR/assets/images/swap_v_baseRed.amd) \
        $$quote($$BASEDIR/assets/images/swap_v_baseRed.png) \
        $$quote($$BASEDIR/assets/images/train_icon.png) \
        $$quote($$BASEDIR/assets/images/user.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/cancellato.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/cancellazione.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/deviazione.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/fermata_soppressa.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/fermata_straordinaria.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/gia_percorso.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/non_percorso.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/numerazioni.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/regolare.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/riprogrammato.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/ritardo01.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/ritardo02.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/ritardo03.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/variato.png) \
        $$quote($$BASEDIR/assets/images/vt_static/img/legenda/icone_legenda/variato_percorso.png) \
        $$quote($$BASEDIR/assets/images/zoom-or-search-tool_318-34054.jpg) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/mindw120h120du/AreaPersonale.qml) \
        $$quote($$BASEDIR/assets/mindw120h120du/CustomTimelineView_.qml) \
        $$quote($$BASEDIR/assets/mindw120h120du/FermataDetail.qml) \
        $$quote($$BASEDIR/assets/mindw120h120du/Ricerca.qml) \
        $$quote($$BASEDIR/assets/mindw76h128du/AreaPersonale.qml) \
        $$quote($$BASEDIR/assets/mindw76h128du/CustomTimelineView_.qml) \
        $$quote($$BASEDIR/assets/mindw76h128du/FermataDetail.qml) \
        $$quote($$BASEDIR/assets/mindw76h128du/Ricerca.qml) \
        $$quote($$BASEDIR/assets/mindw76h128du/StatoTreno_.qml) \
        $$quote($$BASEDIR/assets/mindw76h128du/StazioneItem.qml) \
        $$quote($$BASEDIR/assets/utils.js)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/ArtifactRequest.cpp) \
        $$quote($$BASEDIR/src/ItaloRequest.cpp) \
        $$quote($$BASEDIR/src/ItaloStatusRequest.cpp) \
        $$quote($$BASEDIR/src/LocalDataManager.cpp) \
        $$quote($$BASEDIR/src/NewsRequest.cpp) \
        $$quote($$BASEDIR/src/ProfileRequest.cpp) \
        $$quote($$BASEDIR/src/StatusRequest.cpp) \
        $$quote($$BASEDIR/src/StazioneStatusRequest.cpp) \
        $$quote($$BASEDIR/src/TrainRequest.cpp) \
        $$quote($$BASEDIR/src/app.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/simplecypt.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/ArtifactRequest.hpp) \
        $$quote($$BASEDIR/src/ItaloRequest.hpp) \
        $$quote($$BASEDIR/src/ItaloStatusRequest.hpp) \
        $$quote($$BASEDIR/src/LocalDataManager.hpp) \
        $$quote($$BASEDIR/src/NewsRequest.hpp) \
        $$quote($$BASEDIR/src/ProfileRequest.hpp) \
        $$quote($$BASEDIR/src/StatusRequest.hpp) \
        $$quote($$BASEDIR/src/StazioneStatusRequest.hpp) \
        $$quote($$BASEDIR/src/TrainRequest.hpp) \
        $$quote($$BASEDIR/src/app.hpp) \
        $$quote($$BASEDIR/src/simplecrypt.h)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/vt_static/*.qml) \
        $$quote($$BASEDIR/../assets/images/vt_static/*.js) \
        $$quote($$BASEDIR/../assets/images/vt_static/*.qs) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/*.qml) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/*.js) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/*.qs) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/legenda/*.qml) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/legenda/*.js) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/legenda/*.qs) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/legenda/icone_legenda/*.qml) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/legenda/icone_legenda/*.js) \
        $$quote($$BASEDIR/../assets/images/vt_static/img/legenda/icone_legenda/*.qs) \
        $$quote($$BASEDIR/../assets/mindw120h120du/*.qml) \
        $$quote($$BASEDIR/../assets/mindw120h120du/*.js) \
        $$quote($$BASEDIR/../assets/mindw120h120du/*.qs) \
        $$quote($$BASEDIR/../assets/mindw76h128du/*.qml) \
        $$quote($$BASEDIR/../assets/mindw76h128du/*.js) \
        $$quote($$BASEDIR/../assets/mindw76h128du/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
